[uwsgi]
chdir = /srv/dmoj/site
pythonpath = /srv/dmoj/site
virtualenv = /srv/dmoj/venv

module = dmoj.wsgi:application
env = DJANGO_SETTINGS_MODULE=dmoj.settings
master = true
protocol = uwsgi

uid = dmoj
gid = dmoj
uwsgi-socket = /run/dmoj/site.sock
chmod-socket = 660
pidfile = /run/dmoj/site.pid

workers = 4
threads = 2
listen = 128
buffer-size = 65535
