# Generated by Django 5.2.17 on 2026-09-18 04:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0154_contest_balloons'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestclarification',
            name='team_participation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='team_clarifications', to='judge.contestparticipation'),
        ),
        migrations.AddField(
            model_name='contest',
            name='participation_mode',
            field=models.CharField(choices=[('individual', 'Individual'), ('team', 'Equipos'), ('mixed', 'Mixto')], default='individual', max_length=10, verbose_name='Modalidad de participación'),
        ),
        migrations.AddField(
            model_name='contest',
            name='team_max_size',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Máximo de integrantes'),
        ),
        migrations.AddField(
            model_name='contest',
            name='team_min_size',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Mínimo de integrantes'),
        ),
        migrations.AddField(
            model_name='contestparticipation',
            name='team_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='judge.contestparticipation', verbose_name='current contest'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre del equipo')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_teams', to='judge.profile')),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'equipos',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='contestparticipation',
            unique_together={('contest', 'user', 'virtual')},
        ),
        migrations.AddField(
            model_name='contest',
            name='private_teams',
            field=models.ManyToManyField(blank=True, help_text='Equipos que pueden acceder e inscribirse en este concurso privado.', related_name='private_contests', to='judge.team', verbose_name='Equipos autorizados'),
        ),
        migrations.AddField(
            model_name='contestparticipation',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='judge.team'),
        ),
        migrations.AlterUniqueTogether(
            name='contestparticipation',
            unique_together={('contest', 'team', 'virtual'), ('contest', 'user', 'virtual')},
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='judge.profile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='judge.team')),
            ],
            options={
                'unique_together': {('team', 'profile')},
            },
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', through='judge.TeamMembership', to='judge.profile'),
        ),
        migrations.CreateModel(
            name='ContestTeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_roster', to='judge.contestparticipation')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_contest_entries', to='judge.profile')),
            ],
            options={
                'unique_together': {('participation', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aceptada'), ('D', 'Rechazada'), ('C', 'Cancelada')], default='P', max_length=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invitations', to='judge.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_team_invitations', to='judge.profile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='judge.team')),
            ],
            options={
                'ordering': ('-created', '-id'),
                'indexes': [models.Index(fields=['recipient', 'status'], name='team_invite_inbox')],
            },
        ),
        migrations.CreateModel(
            name='ContestTeamLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=60)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_locations', to='judge.contest')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balloon_locations', to='judge.team')),
            ],
            options={'unique_together': {('contest', 'team')}},
        ),
    ]
